services:
  # Web service (Django application)
  - type: web
    name: school-website
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn school_website.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.4"  # Using 3.11 instead of 3.12 to avoid compatibility issues
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,school-website.onrender.com"
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: "4"

  # Database (PostgreSQL)
databases:
  - name: school-db
    databaseName: school
    user: school
    plan: free 